spring:
  profiles:
    active: pro
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false  # 彻底关闭 Flyway
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8003

---
spring:
  config:
    activate:
      on-profile: pro
  datasource:
  # 3307=301=Bupt@2023 lab-bendi-3306-Bupt@2023
    url: jdbc:mysql://127.0.0.1:3307/well?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Bupt@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
