package club.yunzhi.api.workReview.service;

import club.yunzhi.api.workReview.dto.PendingDrillWellSaveDto;
import club.yunzhi.api.workReview.entity.PendingDrillWell;
import club.yunzhi.api.workReview.entity.TrajectoryDesignResult;
import club.yunzhi.api.workReview.repository.PendingDrillWellRepository;
import club.yunzhi.api.workReview.trajectory.WellPathCalculator;
import club.yunzhi.api.workReview.trajectory.WellTrajectoryConfig;
import club.yunzhi.api.workReview.util.SurveyTrajectoryExcelBuilder;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;

@Service
public class PendingDrillWellServiceImpl implements PendingDrillWellService {

    private final PendingDrillWellRepository repository;
    private final ObjectMapper objectMapper;

    public PendingDrillWellServiceImpl(PendingDrillWellRepository repository, ObjectMapper objectMapper) {
        this.repository = repository;
        this.objectMapper = objectMapper;
    }

    @Override
    @Transactional
    public PendingDrillWell save(PendingDrillWellSaveDto dto) {
        if (dto.getSiteId() == null) {
            throw new IllegalArgumentException("待钻井须归属井场，siteId 不能为空");
        }
        if (dto.getSevenSegmentParams() == null || dto.getSevenSegmentParams().isEmpty()) {
            throw new IllegalArgumentException("sevenSegmentParams 不能为空");
        }
        PendingDrillWell e = new PendingDrillWell();
        e.setSiteId(dto.getSiteId());
        e.setName(dto.getName() != null && !dto.getName().trim().isEmpty() ? dto.getName().trim() : "待钻井");
        e.setWellheadE(dto.getWellheadE());
        e.setWellheadN(dto.getWellheadN());
        e.setWellheadD(dto.getWellheadD());
        e.setTargetE(dto.getTargetE());
        e.setTargetN(dto.getTargetN());
        e.setTargetD(dto.getTargetD());
        e.setFinalDeviation(dto.getFinalDeviation());
        e.setOptimizationTime(dto.getOptimizationTime());
        try {
            e.setSevenSegmentParamsJson(objectMapper.writeValueAsString(dto.getSevenSegmentParams()));
        } catch (JsonProcessingException ex) {
            throw new IllegalArgumentException("七段式参数无法序列化为 JSON", ex);
        }

        attachAutoGeneratedSurveyExcel(e, dto);

        return repository.save(e);
    }

    /**
     * 优先使用前端传入的设计轨迹点（与 3D 图同源）；否则用七段式参数与井口/靶点在服务端重算。
     */
    private void attachAutoGeneratedSurveyExcel(PendingDrillWell e, PendingDrillWellSaveDto dto) {
        try {
            double[][] trajEnd = trajectoryPointsToTrajEnd(dto.getTrajectoryPoints());
            if (trajEnd == null) {
                WellTrajectoryConfig cfg = new WellTrajectoryConfig();
                if (dto.getWellheadE() != null) {
                    cfg.E_wellhead = dto.getWellheadE();
                }
                if (dto.getWellheadN() != null) {
                    cfg.N_wellhead = dto.getWellheadN();
                }
                if (dto.getWellheadD() != null) {
                    cfg.D_wellhead = dto.getWellheadD();
                }
                if (dto.getTargetE() != null) {
                    cfg.E_target = dto.getTargetE();
                }
                if (dto.getTargetN() != null) {
                    cfg.N_target = dto.getTargetN();
                }
                if (dto.getTargetD() != null) {
                    cfg.D_target = dto.getTargetD();
                }

                double[] seg = sevenSegmentMapToArray(dto.getSevenSegmentParams());
                WellPathCalculator calc = new WellPathCalculator(cfg);
                WellPathCalculator.CoordinateResult cr = calc.calculateSevenSegmentCoordinates(seg);
                if (cr.points == null || cr.points.length != 3 || cr.points[0].length < 2) {
                    return;
                }
                trajEnd = cr.points;
            }
            byte[] xlsx = SurveyTrajectoryExcelBuilder.buildFromTrajectoryEnd(trajEnd);
            e.setTrajectoryFileContent(xlsx);
            e.setTrajectoryFileName(sanitizeFileName(e.getName()) + "_井斜数据表.xlsx");
            e.setTrajectoryFileSize((long) xlsx.length);
        } catch (IOException ex) {
            throw new IllegalStateException("根据设计轨迹生成 Excel 失败", ex);
        }
    }

    /**
     * @return [3][n] 的 E/N/D，点数不足时返回 null
     */
    private static double[][] trajectoryPointsToTrajEnd(List<TrajectoryDesignResult.TrajectoryPoint> points) {
        if (points == null || points.size() < 2) {
            return null;
        }
        double[][] rows = NeighborWellTrajectoryService.trajectoryPointsToArray(points);
        if (rows == null || rows.length < 2) {
            return null;
        }
        int n = rows.length;
        double[][] traj = new double[3][n];
        for (int i = 0; i < n; i++) {
            traj[0][i] = rows[i][0];
            traj[1][i] = rows[i][1];
            traj[2][i] = rows[i][2];
        }
        return traj;
    }

    private static double[] sevenSegmentMapToArray(Map<String, Object> map) {
        String[] names = WellTrajectoryConfig.SEVEN_SEG_PARAM_NAMES;
        double[] arr = new double[12];
        for (int i = 0; i < 12; i++) {
            Object v = map.get(names[i]);
            if (v == null) {
                throw new IllegalArgumentException("缺少七段式参数: " + names[i]);
            }
            arr[i] = toDouble(v);
        }
        return arr;
    }

    private static double toDouble(Object v) {
        if (v instanceof Number) {
            return ((Number) v).doubleValue();
        }
        return Double.parseDouble(String.valueOf(v).trim());
    }

    private static String sanitizeFileName(String name) {
        if (name == null || name.trim().isEmpty()) {
            return "pending";
        }
        return name.trim().replaceAll("[\\\\/:*?\"<>|]", "_");
    }

    @Override
    public List<PendingDrillWell> getAll() {
        return repository.findAllByOrderByIdDesc();
    }

    @Override
    public List<PendingDrillWell> getBySiteId(Long siteId) {
        return repository.findBySiteIdOrderByIdDesc(siteId);
    }

    @Override
    public PendingDrillWell getById(Long id) {
        return repository.findById(id).orElseThrow(() -> new NoSuchElementException("待钻井不存在: " + id));
    }

    @Override
    @Transactional
    public void delete(Long id) {
        if (!repository.existsById(id)) {
            throw new NoSuchElementException("待钻井不存在: " + id);
        }
        repository.deleteById(id);
    }

    @Override
    @Transactional
    public void attachTrajectoryExcel(Long id, MultipartFile file) {
        if (file == null || file.isEmpty()) {
            throw new IllegalArgumentException("文件不能为空");
        }
        PendingDrillWell e = getById(id);
        try {
            byte[] bytes = file.getBytes();
            e.setTrajectoryFileContent(bytes);
            e.setTrajectoryFileName(file.getOriginalFilename() != null ? file.getOriginalFilename() : "trajectory.xlsx");
            e.setTrajectoryFileSize((long) bytes.length);
            repository.save(e);
        } catch (IOException ex) {
            throw new IllegalStateException("读取上传文件失败", ex);
        }
    }

    @Override
    public byte[] getTrajectoryExcelContent(Long id) {
        PendingDrillWell e = getById(id);
        if (e.getTrajectoryFileContent() == null || e.getTrajectoryFileContent().length == 0) {
            throw new NoSuchElementException("该待钻井未关联轨迹 Excel");
        }
        return e.getTrajectoryFileContent();
    }

    @Override
    public String getTrajectoryExcelFileName(Long id) {
        PendingDrillWell e = getById(id);
        if (e.getTrajectoryFileName() == null || e.getTrajectoryFileName().isEmpty()) {
            return "trajectory.xlsx";
        }
        return e.getTrajectoryFileName();
    }
}
